version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3016:3016/tcp"
      - "10000-10100:10000-10100/tcp"
      - "10000-10100:10000-10100/udp"
    env_file:
      - .env